### ISSUE TITLE
Browsermob proxy should work from behind a proxy

### ISSUE THREAD

**Issue by dereke** [webmetrics/browsermob-proxy#1]
I have a browsermob proxy running within our corporate network. To access the internet we need to go through a proxy. 

Currently you cannot tell browsermob to use a proxy so it is unusable in this setup.

Please add the ability to specify a proxy server to forward requests to.

**Comment by ClaudiuMuresan** [comment]
I have the same issue with current snapshot release.
I intend to use BrowserMob for profiling more then one web applications in our company so it is must to have this feature implemented.

**Comment by nmcconom** [comment]
I think this would be a useful feature to have to specify a hostname and port that it will forward requests on to.

**Comment by dereke** [comment]
I have fixed this issue with this patch https://github.com/webmetrics/browsermob-proxy/pull/11
It is fairly simplistic - I only need an http proxy at this stage so have only added that.
