### ISSUE TITLE
Cookie duplication

### ISSUE THREAD

**Issue by jaygen** [webmetrics/browsermob-proxy#104]
Hi,

browsermob-proxy (with the latest git revision) is presently duplicating cookies in some cases.

You can test this like so:
1. Point browser to http://www.html-kit.com/tools/cookietester/
2. Press Set Test Cookie
3. On the resulting page, observe that two copies of the cookie are present.

After much digging around I found that the RequestAddCookies Interceptor was adding cookies from the CookieStore to the request headers even though the Cookies header for those cookies existed. It also decides that the cookies are of version 0 and thus it adds a Cookies2 version header even though Cookies2 was obsoleted by RFC-6265.

I didn't bother to look around to see if the Cookies header was supposed to have been removed at some point, I just disabled the RequestAddCookies interceptor by adding 

```
httpClient.getParams().setParameter(ClientPNames.COOKIE_POLICY, CookiePolicy.IGNORE_COOKIES);
```

to the BrowserMobHttpClient constructor. This ruins the cookie parsing that RequestCookiesInterceptor is attempting to do, but I'd rather have unparsed cookies in my hars than be duplicating cookie headers. This issue was rather hard to track down because it only affected one client who has a .NET backend which deals with duplicate cookies by joining them with a comma. :persevere:

**Comment by lightbody** [comment]
Thanks for the report. I'll see what I can do.

**Comment by lightbody** [comment]
FYI -- I'm working on this right now.

**Comment by lightbody** [comment]
Update: I have failing tests written. Now I'm trying to figure out what @gomezd was doing back in #16, which seems to be related to all this.

**Comment by jaygen** [comment]
Thank you, Patrick :sunglasses:
