### ISSUE TITLE
Section SSL Support in README seems to be incorrect

### ISSUE THREAD

**Issue by abotalov** [webmetrics/browsermob-proxy#115]
[Section SSL support of this project's README](https://github.com/webmetrics/browsermob-proxy#ssl-support) says that:

> While the proxy supports SSL, it requires that a Certificate Authority be installed in to the browser. This allows the browser to trust all the SSL traffic coming from the proxy, which will be proxied using a classic man-in-the-middle technique.

However, currently I use Browsermob as a proxy to connect to HTTPS site without importing certificate to browser.

I just create new Firefox profile, set its HTTP and SSL proxy to selenium as follows:

``` ruby
# Initialize browsermob_proxy as shown here - https://github.com/jarib/browsermob-proxy-rb/#how-to-use-with-selenium-webdriver
profile = Selenium::WebDriver::Firefox::Profile.new
profile.proxy = browsermob_proxy.selenium_proxy(:http, :ssl)
```

After that Browsermob seems to support SSL even though README says that API user should import certificate to browser.

**Comment by lightbody** [comment]
That is because the Firefox profile set up by Selenium includes the CA by default. It's just a little thing we do to make Selenium + BMP usage super easy :)
