### ISSUE TITLE
Support /etc/hosts for name resolution

### ISSUE THREAD

**Issue by henryju** [webmetrics/browsermob-proxy#14]
Hi,

I have defined the following host definition in /etc/hosts
127.0.0.1 localhost mycomputer.mycompany.org

Then I tried to use BrowserMob Proxy but name resolution failed:

15:30:17.973 DEBUG o.b.proxy.jetty.http.HttpContext - Handler org.browsermob.proxy.BrowserMobProxyHandler in HttpContext[/,/]
15:30:17.981 DEBUG o.b.p.http.BrowserMobHttpClient$1 - Get connection: HttpRoute[{}->http://mycomputer.mycompany.com:8082], timeout = 60000
15:35:47.826 DEBUG o.b.p.http.BrowserMobHttpClient$1 - Released connection is not reusable.
INFO 09/21 13:35:47 o.b.p.h.BrowserMobH~ - java.net.UnknownHostException: mycomputer.mycompany.com when requesting http://mycomputer.mycompany.com:8082/xxxxxxxxx

Thanks

**Comment by lightbody** [comment]
This is already supported with the remapHost function.
