### ISSUE TITLE
Unable to read response with a HttpResponseInterceptor

### ISSUE THREAD

**Issue by henryju** [webmetrics/browsermob-proxy#15]
If I read the content of the response from the inside of the interceptor callback, I then receive the following error:
org.openqa.selenium.WebDriverException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 1031; received: 0

If I only keep a reference on the HttpResponse object then try to read it after the response is completely processed, I get the following error:
java.lang.RuntimeException: java.io.IOException: Attempted read from closed stream.

Maybe should you wrap the response object to allow reading the stream several times.

Thanks

**Comment by benjaminhawkeslewis** [comment]
You can use [BufferedHttpEntity](http://hc.apache.org/httpcomponents-core-ga/httpcore/apidocs/org/apache/http/entity/BufferedHttpEntity.html). I'm not clear on whether this might have an impact on timing information in the Har log.

``` java
proxyServer.addResponseInterceptor(
    new HttpResponseInterceptor() {

        @Override
        public void process(HttpResponse response, HttpContext context)
                throws HttpException, IOException {
            response.setEntity(new BufferedHttpEntity(response.getEntity()));
            // do stuff with response.getEntity().getContent();
        }

    }       
);
```

**Comment by henryju** [comment]
It works fine. Many thanks.

I'm not using Har log so I don't mind the impact. ;)
