### ISSUE TITLE
Update of selenium-api

### ISSUE THREAD

**Issue by olmorigolo** [webmetrics/browsermob-proxy#18]
Hi,

I would appreciate an update of the selenium-api dependency since the integrated version is quite out of date and many features and bugfixes had been implemented since then.

Is this possible?

So far, very nice tool!

Olmo

**Comment by lightbody** [comment]
Has the API changed? Or are you just concerned about the transitive dependency pulling in an old version?

**Comment by olmorigolo** [comment]
Hi,

I had some trouble with the dependencies. I use my own library for tests that extends the selenium-api. I wanted to integrate browsermob-proxy. Since my library already integrates selenium-api version 2.10, I couldn't add a dependency to browsermob-proxy because browsermob-proxy itselfs add the dependency to the old selenium-api.

The current version of the selenium-api is 2.11 as far as I know.

Cheers,
Olmo

**Comment by lightbody** [comment]
OK, we should probably pin to a newer version of Selenium anyway. We'll get that going soon, but patches are always welcome :)

**Comment by nirvdrum** [comment]
Looks like this can be closed.  2.20 is pulled into 2.0 beta 6.

**Comment by daggarwal** [comment]
Can we update the selenium dependency to 2.28.0 version for 2.0 beta 8 release?

**Comment by lightbody** [comment]
Did even better and upgraded to 2.29.1
