### ISSUE TITLE
SSL Certificate is working not properly

### ISSUE THREAD

**Issue by ghost** [webmetrics/browsermob-proxy#22]
Hi guys,

I`ve tried to use SSL connection, however I got problems:
- under FF3: Secure Connection Failed page with message 'Error code: ssl_error_internal_error_alert'
- under IE8: There is a problem with this website's security certificate page, where every time I need to manually 'Continue to this website (not recommended).'

To be clear:
- original browsermob-proxy-2.0-beta-3 used (any changes in pom.xml dependencies)
- JDK 1.7.0_01 used (with JDK 1.5 I got compile errors - even that you recommend to use bouncycastle with bcprov-jdk15)
- certicate cybervillainsCA.cer imported to both browsers

Any ideas what to do else?

**Comment by ghost** [comment]
Please note, that Ive just compiled project in JDK 1.6.0_29 and its working just fine :)

So it`s possibly the JDK 7 issue.

**Comment by revirdbew** [comment]
I just had the same issue with posting on twitter. I switched from Jre 1.70.1 to jre-6u29-windows-x64. http://www.oracle.com/technetwork/java/javase/downloads/jre-6u29-download-513650.html Now it is working great. Thanks kaftee!

**Comment by lightbody** [comment]
Looks like you're all set?

**Comment by chethan** [comment]
Does this issue still persist for jdk 1.7
