### ISSUE TITLE
Problem compiling the code in the read-only repo

### ISSUE THREAD

**Issue by ghost** [webmetrics/browsermob-proxy#31]
Hi,

I just cloned the read only repo (git clone https://github.com/webmetrics/browsermob-proxy.git) and I am trying to build it, but I am not able due to the following error:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Building BrowserMob Proxy
[INFO]    task-segment: [compile]
[INFO] ------------------------------------------------------------------------
[INFO] [enforcer:enforce {execution: enforce-maven}]
[INFO] [resources:resources {execution: default-resources}]
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 14 resources
[INFO] [compiler:compile {execution: default-compile}]
[INFO] Compiling 444 source files to D:\Users\MyUser\My Documents\Projects\browsermob-proxy\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[131,25] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[131,58] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[131,59] not a statement
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[131,66] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[156,26] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[156,50] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[156,59] not a statement
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[156,68] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[161,4] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[161,33] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[161,49] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,4] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,11] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,17] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,24] not a statement
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,39] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[173,8] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[175,8] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[175,32] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[178,8] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[178,35] '.class' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[178,39] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[182,8] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[182,26] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[186,8] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[186,15] illegal start of expression
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[186,27] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[186,36] ';' expected
[ERROR] \Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[190,1] reached end of file while parsing
[INFO] 29 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Compilation failure

\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[131,25] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[131,58] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[131,59] not a statement
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[131,66] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[156,26] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[156,50] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[156,59] not a statement
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[156,68] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[161,4] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[161,33] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[161,49] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,4] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,11] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,17] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,24] not a statement
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[172,39] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[173,8] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[175,8] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[175,32] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[178,8] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[178,35] '.class' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[178,39] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[182,8] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[182,26] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[186,8] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[186,15] illegal start of expression
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[186,27] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[186,36] ';' expected
\Users\MyUser\My Documents\Projects\browsermob-proxy\src\main\java\org\browsermob\proxy\bricks\ProxyResource.java:[190,1] reached end of file while parsing

[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3 seconds
[INFO] Finished at: Mon Jan 23 17:02:18 CET 2012
[INFO] Final Memory: 21M/68M
[INFO] ------------------------------------------------------------------------

I am using JDK 1.6.0_30 and maven 2.2.1.

Any ideas?

Thanks

M.

**Comment by lightbody** [comment]
Can you try now? I think we had a typo checked in for a bit, but it should be all good now (I just made a 2.0 beta 6 release from source).

**Comment by ghost** [comment]
yes, works perfectly now, thx
