### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by andywuest** [webmetrics/browsermob-proxy#32]
Hi,

is it possible to update the dependencies, so they are more streamlined
with the latest selenium versions. This concerns especially the
httpclient. Especially the usage of th Commons HttpClient should be
updated to the ApacheHttpComponents, since the Commons HttpClient is dead
(http://hc.apache.org/httpclient-3.x/)

Also the Selenium API should be updated to a later version.

**Comment by lightbody** [comment]
We are using Apache Http Components 4.1.3 now and Selenium 2.2.0. Thanks!
