### ISSUE TITLE
Help: Unsure how to *actually* set HTTP Request Headers

### ISSUE THREAD

**Issue by wokkaflokka** [webmetrics/browsermob-proxy#41]
I've been trying to add headers to the proxy using CURL and other methods, but cannot figure out precisely how to format the query. Unfortunately, the docs can't clarify further for me. I presume this is simply a minor issue on my behalf, so I wrote up a quick test script to show what I've been trying. If you can please point me in the right direction, I'd appreciate it.

The script is here: https://gist.github.com/1812932

**Comment by hcliu** [comment]
Was there a resolution? I'm having this issue with beta5 - http://groups.google.com/group/browsermob-proxy/browse_thread/thread/6238ad3097094135

**Comment by wokkaflokka** [comment]
I did not. I stopped bothering and used the Capybara Webkit driver, which allows you to add arbitrary headers.

**Comment by codytan** [comment]
-H "Content-type:json/application"
