### ISSUE TITLE
BrowserMob shouldn't be in the UserAgent

### ISSUE THREAD

**Issue by nirvdrum** [webmetrics/browsermob-proxy#53]
It looks like BrowserMob proxy rewrites the user agent field to insert "BrowserMob RBU."  As a proxy, it shouldn't be touching the user agent field.  It's fair game to insert an X-\* request header, but even that I think is unnecessary.

**Comment by hacklschorsch** [comment]
True.

**Comment by lightbody** [comment]
Fixed!
