### ISSUE TITLE
how can i use the proxy in remote

### ISSUE THREAD

**Issue by reppran** [webmetrics/browsermob-proxy#61]
My  code  is location,  the proxy is remote，how can I use the Function server.remaphost，server.rewriteurl, server.setCaptureContent，server.newHar(initialPageRef)，server.newPage(pageRef)   by java code or command line,

thanks

**Comment by lightbody** [comment]
There is an HTTP REST API for much of the BrowserMob API. It is documented in the readme. Not all functionality is available via the REST API, but we'll be adding more soon.
