### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by davbo** [webmetrics/browsermob-proxy#7]
Currently there seems to be a bug when browsing to SSL pages with the browsermob proxy, see this discussion on the Google groups page for more info:
https://groups.google.com/d/topic/browsermob-proxy/hCgODJFb494/discussion

**Comment by lightbody** [comment]
Good news: this is fixed in 2.0-beta-3, which just got released. Download now from the new website:

http://opensource.webmetrics.com/browsermob-proxy/
