### ISSUE TITLE
No HTTPS when running under JDK 1.7

### ISSUE THREAD

**Issue by Jaizkibel** [webmetrics/browsermob-proxy#71]
HTTPS Requests are not working when Browsermob Proxy is running under Java 7 (64 bit)

Affected versions:

2.0 Beta 6
2.0 Beta 7 SNAPSHOT

**Comment by runwolf** [comment]
I finally got this to work.

had to use the latest bouncycastle bcprov-jdk15on-147 and refactor Browsermob proxy for the changes in the new bouncycastle libray.

**Comment by nirvdrum** [comment]
I believe this was fixed with 36c8631404f3fca26027713d285734e99adf0d20.  If you see otherwise, please re-open.
