### ISSUE TITLE
Some image/gif http requests are missing when capture network traffic by browsermob+webdriver 

### ISSUE THREAD

**Issue by xlzdew** [webmetrics/browsermob-proxy#76]
I tried to capture the networktraffic with browsermob proxy in webdriver, and check some specific image/gif http requests(eg, the request with host name "http://metrics.ford.com"). I ran the test case below, and can get the har file which contains the http requests, but I do not find the specific image/gif http request.

eg:
I can find the request below triggered when I access to page http://www.ford.com/crossovers/edge/features/ in the firefox , but I do not find that request in the har file, seems it missing by the browsermob proxy, does anybody can help me figure it out?(I also attached the generated requests.har file)
Thanks very much,
xlzdew

http://metrics.ford.com/b/ss/fmcfvngprod,fmcglobal/1/H.25/s13405959409143?AQB=1&ndh=1&t=26%2F11%2F2012%2012%3A53%3A41%203%20-480&vmt=4A43B06B&ns=ford&pageName=fv%3A%20vehicle%3A%20feature%3A%20design%3A%20ford%20edge...

public void testTrackingLabel() throws Exception {
    // start the proxy
    ProxyServer server = new ProxyServer(9090);
    server.start();

```
// get the Selenium proxy object
Proxy proxy = server.seleniumProxy();

// configure it as a desired capability
DesiredCapabilities capabilities = new DesiredCapabilities();
capabilities.setCapability(CapabilityType.PROXY, proxy);
WebDriver driver = new FirefoxDriver(capabilities);

// create a new HAR with the label "yahoo.com"sco
server.addRequestInterceptor(new HttpRequestInterceptor() {

    public void process(
            final HttpRequest request,
            final HttpContext context) throws HttpException, IOException {

    }

});

server.newHar("hello");
driver.get("http://www.ford.com/crossovers/edge/features/");
Har har = server.getHar();

String strFilePath = "C:\\test\\requests"+".har";

FileOutputStream fos = new FileOutputStream(strFilePath);
ByteArrayOutputStream baos = new ByteArrayOutputStream();
har.writeTo(baos);
String str = baos.toString();
har.writeTo(fos);


server.stop();
```

}

See the requests.har files here
https://groups.google.com/forum/?fromgroups=#!topic/browsermob-proxy/s5grEuZkeI4

**Comment by lightbody** [comment]
I checked this out and while I can reproduce, I can't tell what is happening. Discussion thread here:

https://groups.google.com/d/topic/browsermob-proxy/s5grEuZkeI4/discussion
