### ISSUE TITLE
cant' find bin/browsermob-proxy 

### ISSUE THREAD

**Issue by andytriboletti** [webmetrics/browsermob-proxy#9]
I ran mvn install and see it created a target folder. I don't see a bin folder.  I tried 
java -jar browsermob-proxy-2.0-beta-3-SNAPSHOT.jar

and got this error

Failed to load Main-Class manifest attribute from
browsermob-proxy-2.0-beta-3-SNAPSHOT.jar

**Comment by lightbody** [comment]
That's because the jar itself isn't enough to run it from the command line. Try this:

   mvn -Prelease install

Then look for browsermob-proxy-2.0-beta-3-SNAPSHOT-bin.zip in the target directory and unpack it. In there you'll find the bin directory :)

**Comment by andytriboletti** [comment]
thanks
