### ISSUE TITLE
JavaDoc

### ISSUE THREAD

**Issue by mlromramse** [webmetrics/browsermob-proxy#93]
Hi guys,

First thanks for a very neat project with lot of potential that we use extensively.

Now to the real issue, I would very much like to see some, preferable complete, javadoc on your classes and methods since this would come up and give clues in the IDE.

**Comment by lightbody** [comment]
Pull requests are welcome :) We'll get docs added over time but probably won't track it as a dedicated issue in the issue tracker. Thanks for the feedback and hope to have more docs for you soon.
